name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint-and-test-backend:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      PORT: 3001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: start test server
        if: false
        run: |
          echo "Pre test"
          npm run start:test > server.log 2>&1 &
          echo "Pre sleep"
          sleep 5
          echo "Post sleep"
          curl http://localhost:3001 -I
          echo "Post curl"
          cat server.log
      - name: Check style
        run: npm run lint
      - name: test
        if: false
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  lint-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: test
        run: npm run test

  deploy-to-fly:
    if: |
      github.event_name == 'push' &&
      !contains(join(toJson(github.event.commits.*.message)), '#skip')
    needs: [lint-and-test-frontend, lint-and-test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: discord webhook_success
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: A new version of bloglist deployed to https://fso-bloglist-zhangtdavid.fly.dev/ by ${{ github.actor }}

  tag_release:
    if: |
      github.event_name == 'push' &&
      !contains(join(toJson(github.event.commits.*.message)), '#skip')
    needs: [lint-and-test-frontend, lint-and-test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  on_failure:
    runs-on: ubuntu-latest
    needs: [lint-and-test-frontend, lint-and-test-backend, deploy-to-fly, tag_release]
    # if: failure()
    if: false
    steps:
      - uses: actions/checkout@v4
      - name: discord webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: commit https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build :(
